name=me_I2C_Console
version=1.0.0
category=Other
architectures=*
sentence=Text console for I2C
paragraph=Text console for [me_I2] module
url=https://github.com/martin-eden/Embedded-me_I2C_Console
author=Martin Eden
maintainer=Martin Eden
depends=me_BaseTypes,me_Menu,me_Console,me_I2C,me_StreamsCollection
